language: node_js
node_js:
- '8'
before_install:
- npm i -g npm@5.6.0
cache:
  directories:
  - node_modules
stages:
- lint
- validate data
- test
- preview deploy
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm test
  - stage: validate data
    script: ajv validate -s ./spec/confs-schema.json -d ./src/data/confs.json
  - stage: preview deploy
    script: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAITYEJ7M6VTSDZHLA
      secret_access_key:
        secure: eoHnoYZbo6dn4D9fLRU9SFwj4sgSMoZ4dICcUMKjXVby+D08xyTB721qMbDPhTCtSCHCgyqrcshQNhV+3y8KV4FM+DCyU2RBjeusCs6/9w1Tldc5Zxbz8iAo8r3MiQTrADqBY5GzsjFo2I1xB7CRnpqfCTfhBPJiFDW0IfBBKhDltRcgo2j9g57UpQ8wHk8PvDzDBssPKjEE7C/LbYIzuBO/2YveLGFgor6JD+XL1UAihSfsalajTuJnAWXGK2r4TnVdz45CXEoEVwnqQUUzyo8ht5YwDEs4FKEOWZD97Qf2FSmSg4WDc+q353KdbIJ73gTa83SsOy3AIlIYf0MGVdA2/smIO0slGuygkFln+roNUjRRP+U8+P78Ua1TGol3tFOpFgJRC1cJAEFDQHfnU/IuHKNhgBtwJZMrzutlww+tJfEkPdN1m3tmM14pAXPSOX9mLZbOgpZE/mvTFaMnLzHUIt4F/rwqwjyFObddd8Dg/N+JpbYBPprCWrY9tx7gr6MC8MmNkdh/5giCuAIYD+piNLgwVDGZUcwXvTM3mn3i2lnXhGnfHFgWpmSanmzfnualZGAgvP9K30v2tXMhznfWMFQJXHNsqQEBsUX1lXkTkLjpTHVHm6HJz5iN1tyqKQ5hZr/eAM5/ecfDX2+eKHA13mu8IgengEY8kiOznP8=
      bucket: xxtechconfspeakers.org
      local-dir: public
      upload-dir: preview
      region: ap-southeast-2
      skip_cleanup: true
      on:
        repo: andeemarks/xxtechconfspeakers-gatsby
  - stage: prod deploy
    script: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAITYEJ7M6VTSDZHLA
      secret_access_key:
        secure: eoHnoYZbo6dn4D9fLRU9SFwj4sgSMoZ4dICcUMKjXVby+D08xyTB721qMbDPhTCtSCHCgyqrcshQNhV+3y8KV4FM+DCyU2RBjeusCs6/9w1Tldc5Zxbz8iAo8r3MiQTrADqBY5GzsjFo2I1xB7CRnpqfCTfhBPJiFDW0IfBBKhDltRcgo2j9g57UpQ8wHk8PvDzDBssPKjEE7C/LbYIzuBO/2YveLGFgor6JD+XL1UAihSfsalajTuJnAWXGK2r4TnVdz45CXEoEVwnqQUUzyo8ht5YwDEs4FKEOWZD97Qf2FSmSg4WDc+q353KdbIJ73gTa83SsOy3AIlIYf0MGVdA2/smIO0slGuygkFln+roNUjRRP+U8+P78Ua1TGol3tFOpFgJRC1cJAEFDQHfnU/IuHKNhgBtwJZMrzutlww+tJfEkPdN1m3tmM14pAXPSOX9mLZbOgpZE/mvTFaMnLzHUIt4F/rwqwjyFObddd8Dg/N+JpbYBPprCWrY9tx7gr6MC8MmNkdh/5giCuAIYD+piNLgwVDGZUcwXvTM3mn3i2lnXhGnfHFgWpmSanmzfnualZGAgvP9K30v2tXMhznfWMFQJXHNsqQEBsUX1lXkTkLjpTHVHm6HJz5iN1tyqKQ5hZr/eAM5/ecfDX2+eKHA13mu8IgengEY8kiOznP8=
      bucket: xxtechconfspeakers.org
      local-dir: public
      region: ap-southeast-2
      skip_cleanup: true
      on:
        repo: andeemarks/xxtechconfspeakers-gatsby