language: node_js
node_js:
- '8'
before_install:
- npm i -g npm@6.2.0
cache:
  directories:
  - node_modules
stages:
- lint
- validate data
- test
- prod deploy
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm test
  - stage: validate data
    script: ajv validate -s ./spec/confs-schema.json -d ./src/data/confs.json
  - stage: prod deploy
    script: npm run build
    deploy:
      provider: s3
      access_key_id: AKIAITYEJ7M6VTSDZHLA
      secret_access_key:
        secure: hIMeyjVZuXVE25u0rePcBIbbQbQ3D7DmY/s40ul6aiv/yP7VBzROGQR8kANmhOe4+jiKVshNu+GRl2IzaFBoItuAn/Q2UHTJFr3DmIJ329RbXOaUZ6C5chHa+1J4KmPb6nE+PQuj93ZUFYbZFjw14tFT0rs3wl459NZA+p3lnHyeegcVl5jElp2AKmiaa3i+VjQYdZz9S/86imYmB8HL+Z+/jD/Yhp7A+Lporw2ja3gGypASBk+eBmXoJfLO3b8j/YgVgZdJbZHfDFq1bpFmnOwOHZuKCe/gChFNi2II6hiQwEf2cWrQGuf0760GlL5jVstNrf9yiko+lal4d9EJNWl0xwWhrE0Onyci1tsJdEwdauwf7XsyiLKlRpa3BSM0xQqdhG9dzaFcCKfi5cEOvEq0D87i3MUS2eWMk1FAnkfOFQ1wka0Ke85Oh6mOVMmzSShdut0SLxAQJ7PF//E0hRv2kwODVKJGYOtjJeZWnLT3KqbXnR/4H89CNA8kHtpOzC00ZsUyMMxhtQYJtkfKLRlUOgqkZEB+azld+7j/NzXanyeq+vT0g+pPtJMWTSaUU3+iYLpHStMO5OTFEaQb+1mk8t2wFt4sHcpBGbZBqa9OCXVJj6J2OmOaQMphOjcQ4i5SYSUzEO4cM8tFg819gSc+tEABfBHqcNAyGHw/YOg=
      bucket: xxtechconfspeakers.org
      local-dir: public
      region: ap-southeast-2
      skip_cleanup: true
      on:
        repo: andeemarks/xxtechconfspeakers-gatsby

