name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Yarn lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Yarn test
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
