name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Yarn lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Yarn test
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy
        uses: actions/checkout@master
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          SOURCE_DIR: 'public'     
